
<script type="text/javascript">

    function console_scroll()
    {
        if (typeof top.$!='function') {
            return;
        }

        dh=$("log_output").scrollHeight
        ch=$("log_output").clientHeight
        if(dh>ch){
            moveme=dh-ch
            $("log_output").scrollTop = moveme;
        }
    }

    function clearOutputPanel()
    {
        var output = $("log_output");
        output.update('');
    }

    function setLogFile()
    {
        this.position = 0;
        this.currentLogFile = $('logSelector').getValue();
        this.clearOutputPanel();
        this.startLiveView();
    }

    function getUpdates() {
        // skip when the last request ist not answered yet
        if(this.running) {
            return;
        }

        this.running = true;
        new Ajax.Request('<?php echo $this->getUrl('adminhtml/logger/liveViewAjax', array('_secure' => Mage::app()->getRequest()->isSecure())) ?>',
            {
                method: 'get',
                parameters: { position: this.position, logFile: this.currentLogFile },
                loaderArea: false,
                onSuccess: function(response) {
                    running = false;
                    var output = $("log_output");
                    var result = response.responseText.evalJSON();

                    logText = result.text.replace(/\n/g, "<br />")

                    if(logText != "<br />") {
                        output.innerHTML += logText;
                    }

                    this.position = result.position;
                }
            });
    }

    function startLiveView()
    {
        getUpdates();

        var pe = new PeriodicalExecuter(
            function(pe) {
                getUpdates();
            }
            , 2);
    }

    document.observe("dom:loaded", function() {
        var position = 0;
        var running = false;
        var currentLogFile = '';

        if (parent && parent.disableInputs) {
            parent.disableInputs(true);
        }

        if (typeof auto_scroll=='undefined') {
            var auto_scroll = window.setInterval(console_scroll, 1);
        }

        if (parent && parent.disableInputs) {
            parent.disableInputs(false);
        }
    });
</script>

<div class="content-header">
    <h3 class="icon-head head-system-account"><?php echo $this->__('Logger Live View'); ?></h3>
</div>
<div class="logger-controls">
    <label for="logSelector">Log-Files:</label>
    <select name="logSelector" id="logSelector">
        <?php $logFiles = $this->getLogFiles(); ?>
        <?php foreach ( $logFiles as $logFile ): ?>
            <option value="<?php echo $logFile; ?>"><?php echo $logFile; ?></option>
        <?php endforeach; ?>
        <?php if(!count($logFiles)): ?>
            <option value=""><?php echo $this->__('No Logfiles found.'); ?></option>
        <?php endif; ?>
    </select>
    <?php if(count($logFiles)): ?>
    <button name="startLiveView" onclick="setLogFile()">
        <span>
            <span>View Log-File</span>
        </span>
    </button>
    <?php endif; ?>
</div>
<div id="log_output" name="log_output">
    <?php if(count($logFiles)): ?>
        <?php echo $this->__('Please select a Log-File.'); ?>
    <?php endif; ?>
</div>
