<div class="form">
    <label for="report_id"><?php echo $this->__('Report Number'); ?>:</label>
    <input type="text" name="report_id" id="report_id"/>
    <input name="submit" id="report_submit" type="button" value="<?php echo $this->__('Submit'); ?>">
</div>
<div id="log_output" name="log_output" style="width:100%; height:500px; overflow: auto; margin: 0px; padding: 3px; background: black; color: #2EC029; font: normal 11px Lucida Console, Courier New, serif;"><?php $this->getLayout()->createBlock('mip/report_log_output')->runHtmlConsole() ?></div>
<script type="text/javascript">
    $('report_submit').observe('click', function(event) {
        new Ajax.Request('<?php echo $this->getUrl('adminhtml/logger/reportAjax', array('_secure' => Mage::app()->getRequest()->isSecure())) ?>',
            {
                method: 'get',
                parameters: { "report_id": $('report_id') },
                loaderArea: false,
                onSuccess: function(response) {
                    var output = $("log_output");
                    var result = response.responseText.evalJSON();

                    logText = result.text.replace(/\n/g, "<br />")

                    if(logText != "<br />") {
                        output.innerHTML = logText;
                    }
                }
            }
        );
    });
</script>