<div class="content-header">
    <h3 class="icon-head head-system-account"><?php echo $this->__('Logger Report View'); ?></h3>
</div>
<div class="logger-controls">
    <label for="report_id"><?php echo $this->__('Report Number'); ?>:</label>
    <input type="text" name="report_id" id="report_id"/>
    <button name="submit" id="report_submit">
        <span>
            <span><?php echo $this->__('Submit'); ?></span>
        </span>
    </button>
</div>
<div id="log_output" name="log_output" style="width:100%; height:500px; overflow: auto; margin: 0px; padding: 3px; background: black; color: #2EC029; font: normal 11px Lucida Console, Courier New, serif;"><?php echo $this->__('Please fill the report id above.'); ?></div>
<script type="text/javascript">
    $('report_id').observe('keypress', function(event) {
        var key = event.which || event.keyCode;
        if(key == Event.KEY_RETURN) {
            $('report_submit').click();
        }
    });
    $('report_submit').observe('click', function(event) {
        $("log_output").innerHTML = '<?php echo $this->__('Loading Report...'); ?>';
        new Ajax.Request('<?php echo $this->getUrl('adminhtml/logger/reportAjax', array('_secure' => Mage::app()->getRequest()->isSecure())) ?>',
            {
                method: 'get',
                parameters: { "report_id": $('report_id').getValue() },
                loaderArea: false,
                onSuccess: function(response) {
                    var output = $("log_output");
                    var result = response.responseText.evalJSON();

                    logText = result.text.replace(/\n/g, "<br />")

                    if(logText != "<br />") {
                        output.innerHTML = logText;
                    }
                }
            }
        );
    });
</script>